name: "Deploy Sphinx to GitHub Pages"

on:
  # runs when pushed to main
  push:
    branches: ["main"]
  
  # enables the action to run manually in the GitHub Actions tab
  workflow_dispatch:

# sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.

# does not cancel any in progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # a job that builds the html and then deploys the built html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build sphinx
        run: |
          pip install -r ./requirements.txt
          make html
      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
